### ISSUE TITLE
Proofread the existing Proof Market documentation

### ISSUE THREAD

**Issue by NickVolynkin** [NilFoundation/proof-market-toolchain#66]
The current docs have a few word choice, punctuation, and style issues. Let's fix them before making significant changes like #63.

- [x] First "Guides" section (also rename it to Getting started) #67 
	- [x] Move documents to `./getting-started` directory, add redirects https://docs.gitbook.com/product-tour/git-sync/content-configuration#how-to-create-a-redirect 
- [x] Economics + Supported proof systems #68 
- [x] User Guides #71 
- [x] Frontend #70
- [x] CMD reference → CLI reference #94 
- [x] Terminology #70
- [x] Requester/Producer Flow https://github.com/NilFoundation/proof-market-toolchain/pull/97
- [x] Mina Proof pipeline https://github.com/NilFoundation/proof-market-toolchain/pull/97
- [x] ignore the Misc section

Make branches from the branch https://github.com/nilfoundation/proof-market-toolchain/tree/00-gitbook-docs.

For each chunk of work, open a PR from your branch → 00-gitbook-docs. Make chunks small enough to make 2-3 PRs a day.
