### ISSUE TITLE
Remove descriptions for multithreaded proof generation

### ISSUE THREAD

**Issue by alexandra-mara** [NilFoundation/proof-market-toolchain#95]
Since multithreaded proof generation is not working yet, we should remove this from documentation, so nobody would try using it.

 - [x] User guides - fixed by #71 
 - [x] [Installation page](https://docs.nil.foundation/proof-market/getting-started/installation) - fixed by #102 
 - [x] Requester-producer flow - fixed by #102 

This is how it was described and how it was supposed to work:

To generate proof using the multithreaded version, execute the following:

```bash
cd build
./bin/proof-generator/proof-generator-mt \
    --proof_out <output file> \
    --circuit_input <statement from Proof Market>
    --public_input <public input from Proof Market> \
    --smp <number of threads>
    ----shard0-mem-scale <scale>
```

Proof computation requires temporary space, always allocated to `core0`/`shard0`.
The following flags require attention for multithreaded use:

* `smp` - number of threads.
  This is ideally the number of CPU cores on the system.
  If you have a 16-core CPU & 16 GB RAM, you can set `smp` to 16.
  Each core gets access to 1 GB of RAM, so `core0`/`shard0` will have access to 1 GB of RAM.
* `shard0-mem-scale` - weighted parameter (`weight`) to reserve memory for `shard0`.
  This is a natural number that allows for `shard0` to have more access to RAM in comparison to others.
  If you have a 16-core CPU & 16 GB RAM, you can set `smp` to 8 and `shard0-mem-scale` to 9.

We first compute `ram_per_shard` variable as follows:

```bash
ram_per_shard = TOTAL_RAM / (smp + shard0-mem-scale -1)
              = 16 / (8 + 8)
              = 1
```

Which equates to the following:

* `shard0` RAM =`shard0-mem-scale` \* `ram_per_shard` = 9 GB
* `shard1` .... `shard7` = `ram_per_shard` = 1 GB/per core = 7 GB

You should tune these two variables for the architecture/circuit for which the proof is generated.

There's also a neat trick that we could recommend:

# Linux
--smp $(nproc)

# macOS
--smp $(sysctl -n hw.logicalcpu)

See for example:

    https://github.com/NilFoundation/zkllvm/blob/master/.github/workflows/build_linux.yml#L105
    https://github.com/NilFoundation/zkllvm/blob/master/.github/workflows/build_macos.yml#L77

**Comment by alexandra-mara** [comment]
Actually appears to be fixed by #71 in the docs, no appearances: https://www.google.com/search?q=site%3Adocs.nil.foundation+.%2Fbin%2Fproof-generator%2Fproof-generator-mt&client=firefox-b-d&ei=ScfHZPn8N7Wbi-gPvuSGiAw&ved=0ahUKEwi5xZ6FlrmAAxW1zQIHHT6yAcEQ4dUDCA8&uact=5&oq=site%3Adocs.nil.foundation+.%2Fbin%2Fproof-generator%2Fproof-generator-mt&gs_lp=Egxnd3Mtd2l6LXNlcnAiQXNpdGU6ZG9jcy5uaWwuZm91bmRhdGlvbiAuL2Jpbi9wcm9vZi1nZW5lcmF0b3IvcHJvb2YtZ2VuZXJhdG9yLW10SABQAFgAcAB4AJABAJgBAKABAKoBALgBA8gBAPgBAvgBAeIDBBgAIEE&sclient=gws-wiz-serp

However, we still need to fix this in all the READMEs - PMT's and zkLLVM's, for example
